### PR TITLE
fix(ui): Improve page navigation in `DataTablePagination` component

### LINKED ISSUE #2135: Input field for the page responds too fast to changes
When manually changing the page number in any paginated table, the page is immediately reloaded which makes it impossible to enter a two-digit number as the page. This is problematic when there are many pages, like here:

Image

I tested this only in Firefox, in case the behavior is browser specific.

Instead, there should either be a delay or the reload should only happen when the focus is changed or the enter button is pressed.

### PR DESCRIPTION
**Pull request by bs-ondem**
Handle page changes only when the user presses the "Enter" key or loses focus on the input field.

Resolves #2135.

### CODE REVIEW

**Comment by Etsija** [comment]
LGTM, and I wasn't able to break it when testing, but I'd like @lamppu to have a look as well.

File: ui/src/components/data-table/data-table-pagination.tsx [hunk 1]
```diff
@@ -88,13 +90,18 @@ export function DataTablePagination({
           Page{' '}
           <Input
             type='number'
-            value={currentPage}
+            value={page}
+            onKeyUp={(event) => {
+              if (event.key === 'Enter') {
+                navigate(setCurrentPageOptions(page));
+              }
+            }}
```
Comment (mmurto) [inline ui/src/components/data-table/data-table-pagination.tsx:98]: This could be an accessibility issue. The `Input` should probably be wrapped in a `form` and this should be in the form's `onSubmit` and the input's `onBlur`. The form's `onSubmit` likely requires `event.preventDefault()` to prevent page refresh.

**Review by mmurto — CHANGES_REQUESTED** [review]

File: ui/src/components/data-table/data-table-pagination.tsx (hunk 1 above)
Comment (bs-ondem) [reply ui/src/components/data-table/data-table-pagination.tsx:98]: I'm not sure I fully understand. Do you mean something like this?

    <form ... onSubmit={}>
       <input ... onBlur={}/>
    </form>

So, I would replace the `onKeyUp` event on the input with the `onSubmit` event on the form instead?

Comment (mmurto) [reply ui/src/components/data-table/data-table-pagination.tsx:98]: Yes, exactly like that. That ensures that the action triggers when sending the submit event also on other input methods than keyboard, like assistive tools and touch devices.

Comment (Etsija) [reply ui/src/components/data-table/data-table-pagination.tsx:98]: For the sake of unity, should we actually use a shadcn-ui form here?

Comment (Etsija) [reply ui/src/components/data-table/data-table-pagination.tsx:98]: I guess [this](https://github.com/eclipse-apoapsis/ort-server/blob/68bae311776bf07e005e80fc188a5767bd3ea30c/ui/src/components/header.tsx#L208-L229) could serve as an example of a simplest form which has just one input field.

Comment (mmurto) [reply ui/src/components/data-table/data-table-pagination.tsx:98]: > For the sake of unity, should we actually use a shadcn-ui form here?

I don't think it brings any value over just using the native form. Do you think otherwise?

Comment (Etsija) [reply ui/src/components/data-table/data-table-pagination.tsx:98]: Validation comes to my mind.

**Review by mmurto — APPROVED** [review]
